### PR TITLE
Fixed Porygon evolution issue with strict genders on

### LINKED ISSUE #712: Strict genders preventing evolution for Porygon
* Turn on strict genders
* Add a Porygon
* Level it to 9
* Click Evolve
* **Notice you get the "Pick an Evolution" dialog with 0 entries**
* Expected: It just evolves to Porygon2 (no dialog for this one).

### PR DESCRIPTION
**Pull request by magroader**
Closes #712

### CODE REVIEW

File: pokedex/pokedex.lua [hunk 1]
```diff
@@ -608,7 +612,7 @@ function M.get_evolutions(pokemon, gender)
 	for _, species in pairs(d.into) do
 		if not M.enforce_genders() then
 			table.insert(evolutions, species)
-		elseif genders[species] == nil or (genders[species] and genders[species] == gender) then
+		elseif gender_can_evolve_to(gender, species) then
```
Comment (magroader) [inline pokedex/pokedex.lua:615]: Problem was this logic didn't have `(gender or M.GENDERLESS)`. Moved to a function for automatic consistency.

**Review by Jerakin — APPROVED** [review]
