### PR TITLE
Fixing some issues with edit pokemon screen crashes

### LINKED ISSUE #563: App Crash Gourgeist
Clicking edit on gourgeist crashes app.

iPhone V1.12.4

This was the particular one I was having problems with.

{"level":{"evolved":[14],"caught":1,"current":18},"moves":{"Confuse Ray":{"index":3,"pp":5},"Scary Face":{"index":2,"pp":5},"Leech Seed":{"pp":5,"index":4},"Shadow Sneak":{"index":5,"pp":20},"Trick-or-Treat":{"index":1,"pp":5}},"nickname":"Hemmos","loyalty":3,"abilities":["Pickup","Frisk"],"slot":5,"statuses":[],"number":6,"species":{"current":"Gourgeist","caught":"Pumpkaboo"},"feats":["Extra Move","Resilient (CHA)","AC Up","Tough"],"exp":326000,"attributes":{"DEX":0,"CHA":0,"CON":0,"INT":0,"STR":0,"increased":{"DEX":6,"INT":0,"STR":0,"CHA":7,"WIS":0,"CON":0},"WIS":0,"nature":{"STR":-2,"AC":1}},"hp":{"max":120,"edited":false,"current":184},"id":"bf0fe63d094f8e61278bc604bd62c520","nature":"Nimble"}

### PR DESCRIPTION
**Pull request by magroader**
Fixes #563

Two main issues fixed here:

- Gourgeist in 1.12.4 didn't know who it evolved from. This has since been fixed in data, but the code is less brittle now
- It was possible, by deleting the Extra Move feat, to end up with a corrupted pokemon with a move in slot 5 despite not having the Extra Move feat. This would have crashed the screen. Fixed both the crash and also prevented the corruption from being possible.

### CODE REVIEW

File: pokedex/pokedex.lua [hunk 1]
```diff
@@ -14,6 +14,7 @@ local pokedex
 local pokedex_extra
 local abilities = {}
 local evolvedata
+local evolve_from_data = {}
```
Comment (magroader) [inline pokedex/pokedex.lua:17]: This is just an optimization, not strictly necessary to fix any bugs.

File: pokedex/pokemon.lua [hunk 2]
```diff
@@ -161,14 +163,24 @@ function M.set_held_item(pokemon, item)
...
-			if name == "Extra Move" then
-				M.remove_move(pokemon, M.get_moves_count(pokemon))
-				table.remove(pokemon.feats, i)
-				break
-			end
-			table.remove(pokemon.feats, i)
+	local removed = 0
+	local feats = M.get_feats(pokemon)
+
+	-- Remove every instance of the feat with this name
```
Comment (magroader) [inline pokedex/pokemon.lua:169]: Previously this may not have removed all instances of the feat, depending on how pairs() works (I'm not precisely sure if pairs() lets you remove a thing while iterating it).

File: pokedex/pokemon.lua [hunk 3]
```diff
@@ -391,18 +403,20 @@ function M.get_defaut_max_hp(pokemon)
...
-			local hit_dice = pokedex.get_pokemon_hit_dice(from_pokemon)
-			local hit_dice_current = pokedex.get_pokemon_hit_dice(current)
-			local levels_gained = at_level - from_level
-			local hp_hit_dice = math.ceil((hit_dice + 1) / 2) * levels_gained
-			local hp_evo = at_level * 2
-			-- Offset of current hit dice and the new one
-			local hp_offset = math.ceil((hit_dice_current + 1) / 2) - math.ceil((hit_dice + 1) / 2)
-			evolution_hp = evolution_hp + hp_hit_dice + hp_evo + hp_offset
-			current = from_pokemon
+			if from_pokemon then
```
Comment (magroader) [inline pokedex/pokemon.lua:406]: In 1.12.4 this could crash due to from_pokemon being MissingNo for Gourgeist.

File: pokedex/pokemon.lua [hunk 4]
```diff
@@ -431,7 +445,9 @@ function M.get_evolution_points(pokemon)
 		while next(evolutions) ~= nil do
 			table.remove(evolutions)
 			current = pokedex.get_evolved_from(current)
-			evolution_points = evolution_points + pokedex.evolve_points(current)
+			if current then
```
Comment (magroader) [inline pokedex/pokemon.lua:448]: current can now be nil (previously was MissingNo) so I protected against it just in case.

File: pokedex/pokemon.lua (hunk 2 above)
Comment (Jerakin) [reply pokedex/pokemon.lua:169]: It would only delete the first "Extra Move" because it `break`s. You can only remove one feat at the time so it shouldn't matter (and `pairs` doesn't like you deleting stuff you iterate over it but as we `break` I was being lazy 🙃 )

Comment (magroader) [reply pokedex/pokemon.lua:169]: OK, so I have introduced a new, different bug that every Extra Move feat gets deleted if you delete 1 of them.. is it possible to get more than 1? I would also argue that that bug is less bad than the "totally break the edit screen" bug.

What needs to happen to make this perfect is to remove just 1 Extra Move (ideally the one you clicked the X on but whatever) and then remove the move with index 4+N where N is the number of Extra Move feats you have.

Comment (Jerakin) [reply pokedex/pokemon.lua:169]: We probably don't want to remove all of the feats, the user took an action to remove 1 of the feats. Would feel like a bug if we removed them all. Maybe we should simply remove the "highest" move?
```lua
function M.remove_feat(pokemon, feat)
	local removed = 0
	local feats = M.get_feats(pokemon)

	for i, name in pairs(M.get_feats(pokemon)) do
		if name == feat then
			if name == "Extra Move" then
				M.remove_move(pokemon, M.get_moves_count(pokemon))
				table.remove(pokemon.feats, i)
				break
			end
			table.remove(pokemon.feats, i)
		end
	end

	-- If the feat was extra move, also remove moves with the high indices. There was previously a bug here where if there was a gap in the move set, the move in the last slot would not be removed.
	if feat == "Extra Move" then
		local _, c = M.have_feat(pokemon, "Extra Move")
		M.remove_move(pokemon, M.DEFAULT_MAX_MOVES + c + 1)
	end
end

```

Comment (magroader) [reply pokedex/pokemon.lua:169]: Yep that's exactly what I was saying.

Comment (Jerakin) [reply pokedex/pokemon.lua:169]: Oh, that explains a lot. Was a bit confused over your Discord comment. It had not yet showed up when I wrote it for some reason.

Comment (magroader) [reply pokedex/pokemon.lua]: Fixed! And now it removes the feat you selected rather than the first one / all with that name.

**Comment by magroader** [comment]
Fixes #549
Fixes #550

**Comment by Jerakin** [comment]
This looks good to me now

**Review by Jerakin — APPROVED** [review]
